/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.projetoloja.view.Produto;

import br.com.martinello.controll.model.MetodoBuscaCliente;
import br.com.martinello.controll.model.MetodoBuscaProduto;
import br.com.martinello.projetoloja.Dao.Cliente.DaoAlterarCadastroProdutoSelect;
import br.com.martinello.projetoloja.Dao.Cliente.DaoBuscaCliente;
import br.com.martinello.projetoloja.Dao.Produto.DaoAlterarProduto;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin.carvalho
 */
public class TelaAlterarCadastroProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAlterarCadastroProduto
     */
    public TelaAlterarCadastroProduto() throws SQLException {
        initComponents();
        tabelaAlterarProduto();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAlterarValor = new javax.swing.JTextField();
        txtAlterarQuantidade = new javax.swing.JTextField();
        txtAlterarCategoria = new javax.swing.JComboBox<>();
        txtAlterarDescricao = new javax.swing.JTextField();
        txtAtualizarData = new javax.swing.JFormattedTextField();
        btAlterar = new javax.swing.JButton();
        txtAlterarNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAlterarId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alterarTableProduto = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarProduto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setTitle("Atualizar Cadastro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar dados"));

        jLabel1.setText("Nome");

        jLabel2.setText("Data Fabricação");

        jLabel3.setText("Valor");

        jLabel4.setText("Quantidade");

        jLabel5.setText("Categoria");

        jLabel6.setText("Descrição");

        txtAlterarCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moveis", "Eletrondomesticos", "Eletronicos" }));

        try {
            txtAtualizarData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        jLabel8.setText("Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAtualizarData, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlterarId, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlterarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlterarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlterarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlterarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btAlterar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAlterarId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAtualizarData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAlterarValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAlterarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtAlterarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlterarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(btAlterar))
                .addContainerGap())
        );

        alterarTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_produto", "nome", "valor", "categoteria", "data_execucao", "quantidade"
            }
        ));
        alterarTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                alterarTableProdutoMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(alterarTableProduto);

        jLabel7.setText("Nome");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(txtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        MetodoBuscaProduto metodoBuscaProduto = new MetodoBuscaProduto();

        metodoBuscaProduto.setNome(title);
        metodoBuscaProduto.setDataFabricacao(title);
        metodoBuscaProduto.setDescricao(title);
        metodoBuscaProduto.setValor(ERROR);
        metodoBuscaProduto.setQuantidade(WIDTH);
        metodoBuscaProduto.setCategoria(title);

        


    }//GEN-LAST:event_btAlterarActionPerformed

    private void alterarTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarTableProdutoMouseClicked
        // TODO add your handling code here:
        if (alterarTableProduto.getSelectedRow() != -1) {

            txtAlterarId.setText(alterarTableProduto.getValueAt(alterarTableProduto.getSelectedRow(), 0).toString());
            txtAlterarNome.setText(alterarTableProduto.getValueAt(alterarTableProduto.getSelectedRow(), 1).toString());
            txtAlterarQuantidade.setText(alterarTableProduto.getValueAt(alterarTableProduto.getSelectedRow(), 1).toString());

        }
    }//GEN-LAST:event_alterarTableProdutoMouseClicked

    private void alterarTableProdutoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarTableProdutoMouseReleased
        // TODO add your handling code here:
         if (alterarTableProduto.getSelectedRow() != -1) {

            txtAlterarId.setText(alterarTableProduto.getValueAt(alterarTableProduto.getSelectedRow(), 0).toString());
            txtAlterarNome.setText(alterarTableProduto.getValueAt(alterarTableProduto.getSelectedRow(), 1).toString());
            txtAlterarQuantidade.setText(alterarTableProduto.getValueAt(alterarTableProduto.getSelectedRow(), 1).toString());

        }
    }//GEN-LAST:event_alterarTableProdutoMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tableAlterarProsurto(txtBuscarProduto.getText());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    public void tabelaAlterarProduto() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) alterarTableProduto.getModel();
        modelo.setNumRows(0);
        DaoAlterarCadastroProdutoSelect pdao = new DaoAlterarCadastroProdutoSelect();

        for (MetodoBuscaProduto p : pdao.readProduto()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getValor(),
                p.getCategoria(),
                p.getDataExecucao(),
                p.getQuantidade(),});
        }
        
        
        

      public void tabelaAlterarProduto(String nomeProduto) {
        DefaultTableModel modelo = (DefaultTableModel) alterarTableProduto.getModel();
        modelo.setNumRows(0);
        DaoAlterarProduto pdao = new DaoAlterarProduto();

        for (MetodoBuscaProduto p : pdao.daoAlterarProduto()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getValor(),
                p.getCategoria(),
                p.getDataExecucao(),
                p.getQuantidade(),});
        }   
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alterarTableProduto;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> txtAlterarCategoria;
    private javax.swing.JTextField txtAlterarDescricao;
    private javax.swing.JTextField txtAlterarId;
    private javax.swing.JTextField txtAlterarNome;
    private javax.swing.JTextField txtAlterarQuantidade;
    private javax.swing.JTextField txtAlterarValor;
    private javax.swing.JFormattedTextField txtAtualizarData;
    private javax.swing.JTextField txtBuscarProduto;
    // End of variables declaration//GEN-END:variables
}
