/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.projetoloja.view.Produto;

import br.com.martinello.controll.controll.Controll;
import br.com.martinello.controll.model.MetodoAlterarProduto;
import br.com.martinello.controll.model.MetodoBuscaCliente;
import br.com.martinello.controll.model.MetodoBuscaProduto;
import br.com.martinello.projetoloja.Dao.Cliente.DaoAlterarCadastroProdutoSelect;
import br.com.martinello.projetoloja.Dao.Cliente.DaoBuscaCliente;
import br.com.martinello.projetoloja.Dao.Produto.DaoAlterarProduto;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin.carvalho
 */
public class TelaAlterarCadastroProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAlterarCadastroProduto
     */
    public TelaAlterarCadastroProduto() throws SQLException {
        initComponents();
        tabelaAlterarProduto();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAlterarValor = new javax.swing.JTextField();
        txtAlterarQuantidade = new javax.swing.JTextField();
        txtAlterarCategoria = new javax.swing.JComboBox<>();
        txtAlterarDescricao = new javax.swing.JTextField();
        txtAtualizarDataFAbricacao = new javax.swing.JFormattedTextField();
        btAlterar = new javax.swing.JButton();
        txtAtualizarNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAlterarId = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdataExecucao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alterarTableProduto = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarProduto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setTitle("Atualizar Cadastro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar dados"));

        jLabel1.setText("Nome");

        jLabel2.setText("Data Fabricação");

        jLabel3.setText("Valor");

        jLabel4.setText("Quantidade");

        jLabel5.setText("Categoria");

        jLabel6.setText("Descrição");

        txtAlterarCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moveis", "Eletrondomesticos", "Eletronicos" }));

        try {
            txtAtualizarDataFAbricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        jLabel8.setText("Id");

        txtAlterarId.setText("NULL");

        jLabel9.setText("Data do Cadastro:");

        txtdataExecucao.setText("NULL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAtualizarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAtualizarDataFAbricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtAlterarId)
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtdataExecucao))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlterarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlterarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlterarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlterarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btAlterar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAlterarId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtdataExecucao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAtualizarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAtualizarDataFAbricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAlterarValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAlterarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtAlterarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlterarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(btAlterar))
                .addContainerGap())
        );

        alterarTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_produto", "nome", "data_fabricacao", "Descricao", "valor", "quantidade", "categoria", "data_execucao"
            }
        ));
        alterarTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(alterarTableProduto);

        jLabel7.setText("Nome");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(txtBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        MetodoAlterarProduto metodoAlterarProduto = new MetodoAlterarProduto();
        LocalDate hoje = LocalDate.now();
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        Controll controll = new Controll();

        try {

            metodoAlterarProduto.setId(Integer.parseInt(txtAlterarId.getText()));
            metodoAlterarProduto.setNome(txtAtualizarNome.getText());
            metodoAlterarProduto.setDataFabricacao(txtAtualizarDataFAbricacao.getText());
            metodoAlterarProduto.setDescricao(txtAlterarDescricao.getText());
            metodoAlterarProduto.setValor(Double.parseDouble(txtAlterarValor.getText()));
            metodoAlterarProduto.setQuantidade(Integer.parseInt(txtAlterarQuantidade.getText()));
            metodoAlterarProduto.setCategoria(txtAlterarCategoria.getSelectedItem().toString());
            //metodoBuscaProduto.setUltimaAlteracao(hoje.format(formatador));

            controll.InsertProduto(metodoAlterarProduto);
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro foi " + ex);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btAlterarActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //tabelaAlterarProduto(txtBuscarProduto.getText());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void alterarTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarTableProdutoMouseClicked
        // TODO add your handling code here:

        int linha = alterarTableProduto.getSelectedRow();

        txtAlterarId.setText(alterarTableProduto.getValueAt(linha, 0).toString());
        txtAtualizarNome.setText((alterarTableProduto.getValueAt(linha, 1).toString()));
        txtAtualizarDataFAbricacao.setText(alterarTableProduto.getValueAt(linha, 2).toString());
        txtAlterarDescricao.setText(alterarTableProduto.getValueAt(linha, 3).toString());
        txtAlterarValor.setText(alterarTableProduto.getValueAt(linha, 4).toString());
        txtAlterarQuantidade.setText(alterarTableProduto.getValueAt(linha, 5).toString());
        txtdataExecucao.setText(alterarTableProduto.getValueAt(linha, 7).toString());

    }//GEN-LAST:event_alterarTableProdutoMouseClicked

    public void tabelaAlterarProduto() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) alterarTableProduto.getModel();
        modelo.setNumRows(0);
        DaoAlterarCadastroProdutoSelect pdao = new DaoAlterarCadastroProdutoSelect();

        for (MetodoBuscaProduto p : pdao.readProduto()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getDataFabricacao(),
                p.getDescricao(),
                p.getValor(),
                p.getQuantidade(),
                p.getCategoria(),
                p.getDataExecucao(),});
        }

//      public void tabelaselecProduro(String nomeProduto) {
//        DefaultTableModel modelo = (DefaultTableModel) alterarTableProduto.getModel();
//        modelo.setNumRows(0);
//        DaoAlterarProduto pdao = new DaoAlterarProduto();
//
//        for (MetodoBuscaProduto p : pdao.daoAlterarProduto()) {
//            modelo.addRow(new Object[]{
//                p.getId(),
//                p.getNome(),
//                p.getValor(),
//                p.getCategoria(),
//                p.getDataExecucao(),
//                p.getQuantidade(),});
//        }   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alterarTableProduto;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> txtAlterarCategoria;
    private javax.swing.JTextField txtAlterarDescricao;
    private javax.swing.JLabel txtAlterarId;
    private javax.swing.JTextField txtAlterarQuantidade;
    private javax.swing.JTextField txtAlterarValor;
    private javax.swing.JFormattedTextField txtAtualizarDataFAbricacao;
    private javax.swing.JTextField txtAtualizarNome;
    private javax.swing.JTextField txtBuscarProduto;
    private javax.swing.JLabel txtdataExecucao;
    // End of variables declaration//GEN-END:variables
}
