/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.martinello.projetoloja.view.Cliente;

import br.com.martinello.controll.model.MetodoBuscaCliente;
import br.com.martinello.projetoloja.Dao.Cliente.DaoBuscaCliente;
import br.com.martinello.projetoloja.Dao.Cliente.DaoBuscaClienteSelect;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin.carvalho
 */
public class TelaBuscaCliente extends javax.swing.JInternalFrame {

    private JLabel txtNomeCliente;
    private JLabel txtCPFCliente;
    private JLabel txtCelularCliente;
    private JLabel txtLocalidadeCliente;
    private JLabel txtEmailCliente;
    private JLabel txtComplementoCliente;
    private JLabel txtBairroCliente;
    private JLabel txtCepCliente;
    private JLabel txtLogradouroCliente;
    private JLabel txtUfCliente;

    /**
     * Creates new form TelaBuscaCliente
     *
     */
    public TelaBuscaCliente() {

        initComponents();

    }

    public TelaBuscaCliente(JLabel txtNomeCliente, JLabel txtCPFCliente,
            JLabel txtCelularCliente, JLabel txtLocalidadeCliente, JLabel txtEmailCliente,
            JLabel txtComplementoCliente, JLabel txtBairroCliente, JLabel txtCepCliente,
            JLabel txtLogradouroCliente, JLabel txtUfCliente) throws SQLException {
        initComponents();
        readTable();

        this.txtNomeCliente = txtNomeCliente;
        this.txtCPFCliente = txtCPFCliente;
        this.txtCelularCliente = txtCelularCliente;
        this.txtLocalidadeCliente = txtLocalidadeCliente;
        this.txtEmailCliente = txtEmailCliente;
        this.txtComplementoCliente = txtComplementoCliente;
        this.txtBairroCliente = txtBairroCliente;
        this.txtCepCliente = txtCepCliente;
        this.txtLogradouroCliente = txtLogradouroCliente;
        this.txtUfCliente = txtUfCliente;

    }

    // TODO add your handling code here:
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeBuscaCliente = new javax.swing.JTable();
        btBusca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btInserir = new javax.swing.JButton();
        txtCampoDeBuscaCliente = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(685, 350));

        tabelaDeBuscaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_Cliente", "nome", "cpf", "Celular", "localidade", "email", "complemento", "bairro", "cep", "logradouro", "uf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDeBuscaCliente);
        tabelaDeBuscaCliente.getAccessibleContext().setAccessibleName("");

        btBusca.setText("Buscar");
        btBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaActionPerformed(evt);
            }
        });

        jLabel1.setText("Campos de buscas");

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(587, 587, 587)
                        .addComponent(btInserir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCampoDeBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(btBusca)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCampoDeBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBusca))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btInserir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   MetodoBuscaCliente metodoBuscaCliente = new MetodoBuscaCliente();
    private void btBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaActionPerformed

        try {
            readTableForInt(txtCampoDeBuscaCliente.getText());
        } catch (SQLException ex) {
            Logger.getLogger(TelaBuscaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btBuscaActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        inserir();
        dispose();
    }//GEN-LAST:event_btInserirActionPerformed

    public void readTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tabelaDeBuscaCliente.getModel();
        modelo.setNumRows(0);
        DaoBuscaClienteSelect pdao = new DaoBuscaClienteSelect();

        for (MetodoBuscaCliente p : pdao.read()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCpf(),
                p.getCelular(),
                p.getLocalidade(),
                p.getEmail(),
                p.getComplemento(),
                p.getBairro(),
                p.getCep(),
                p.getLogradouro(),
                p.getUf()});
        }

    }

    public void readTableForInt(String nome) throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tabelaDeBuscaCliente.getModel();
        modelo.setNumRows(0);
        DaoBuscaCliente pdao = new DaoBuscaCliente();

        for (MetodoBuscaCliente p : pdao.daoBuscaCliente(nome)) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCpf(),
                p.getCelular(),
                p.getLocalidade(),
                p.getEmail(),
                p.getComplemento(),
                p.getBairro(),
                p.getCep(),
                p.getLogradouro(),
                p.getUf()});
        }

    }

    public void inserir() {
        int linha = tabelaDeBuscaCliente.getSelectedRow();

        txtNomeCliente.setText((tabelaDeBuscaCliente.getValueAt(linha, 1).toString()));
        txtCPFCliente.setText(tabelaDeBuscaCliente.getValueAt(linha, 2).toString());
        txtCelularCliente.setText(tabelaDeBuscaCliente.getValueAt(linha, 3).toString());
        txtLocalidadeCliente.setText(tabelaDeBuscaCliente.getValueAt(linha, 4).toString());
        txtEmailCliente.setText(tabelaDeBuscaCliente.getValueAt(linha, 5).toString());
        txtComplementoCliente.setText(tabelaDeBuscaCliente.getValueAt(linha, 6).toString());
        txtBairroCliente.setText(tabelaDeBuscaCliente.getValueAt(linha, 7).toString());
        txtCepCliente.setText(tabelaDeBuscaCliente.getValueAt(linha, 8).toString());
        txtLogradouroCliente.setText(tabelaDeBuscaCliente.getValueAt(linha, 9).toString());
        txtUfCliente.setText(tabelaDeBuscaCliente.getValueAt(linha, 10).toString());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBusca;
    private javax.swing.JButton btInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDeBuscaCliente;
    private javax.swing.JTextField txtCampoDeBuscaCliente;
    // End of variables declaration//GEN-END:variables
}
